### ISSUE TITLE
Unclear: Photon Noise Poisson or Gaussian?

### ISSUE THREAD

**Issue by Soxxes** [MLI-lab/deep_inverse_book.github.io#1]
In chapter 3.1, the following excerpt is unclear. Is a Gaussian distribution suitable for both high photon count and low light regime? Or is it a typo? The question arises, because photon noise is said to be Poisson distributed. But then both cases can be modeled by a Gaussian.
If it is not a typo, I suggest adding something like "as well" or "also" at the end of the sentence: "Except in low-light conditions photon noise is the dominant source of noise in a camera and is [also] well modeled by a Gaussian distribution."
![grafik](https://github.com/MLI-lab/deep_inverse_book.github.io/assets/50017993/f80285a0-ce2a-4e1f-81c0-0a998354c5e7)

**Comment by reinhardh** [comment]
I clarified that only in bright conditions, Poisson noise is well approximated by Gaussian noise. Thanks for the comment!
