### ISSUE TITLE
13.3.3) advocate for reader studies?

### ISSUE THREAD

**Issue by davevanveen** [MLI-lab/deep_inverse_book.github.io#10]
at the end of 13.3.3, could be worth explicitly advocating for reader studies in the case of medical imaging or more generally qualitative review by human experts for verifying translational impact. i'm biased, but i believe this is an important step to move the needle for applied imaging.

**Comment by reinhardh** [comment]
Many thanks, very good point. I addressed that by justifying the naming in the respective chapters, and am also considering to explain that in the introduction.
