### ISSUE TITLE
Page 87 - Chapter 8.1.1

### ISSUE THREAD

**Issue by kovioli** [MLI-lab/deep_inverse_book.github.io#11]
Multiplication factor of 2 missing from Proof of Proposition 7:

it is supposed to be
$\mathbb{E}_{x,y,e'} [||f(y)-x+e'||^2_2]=... + \mathbb{E}_{x,y,e'}[2 \cdot(f(y)-x)^Te'] + ...$

**Comment by reinhardh** [comment]
Fixed, thanks!
