### ISSUE TITLE
Ch. 10.3 un-trained networks, minor inconsistency

### ISSUE THREAD

**Issue by Soxxes** [MLI-lab/deep_inverse_book.github.io#12]
In chapter 10.3, proposition 10 (the proof to be precise) says that $v_i$ are the left singular values, where you defined the SVD as $J = W\Sigma V^T$. It is a bit confusing. You define $v_i$ as the columns of $W$ and therefore it is correct. However, in terms of consistency it could be better if the letters match. Also, everywhere else you use $U\Sigma V^T$ for the SVD of a matrix. Is there a specific reason to break with this tradition?

**Comment by reinhardh** [comment]
Thanks, that's a good point, I changed the notation in the chapter so that we now have $U\Sigma V^T$ as usual.
