### ISSUE TITLE
Chapter 9

### ISSUE THREAD

**Issue by ajiljalal** [MLI-lab/deep_inverse_book.github.io#15]
- Intro, right above section 9.1 "generative models with explicitly provide access to a probability
distribution" . Why call them explicit models (GANs for example are implicit)? It feels like in this chapter you're trying to contrast auto-encoders which memorize signals with generative models that allow for sampling, so it feels like explicit vs implicit generative models aren't important? 
- In Section 9.2, maybe it's worth saying that flow-based models also give an estimate of p(x) for free? 
- In Section 9.3, perhaps it's better to say "decoder from an auto-encoder" instead of generator, since you're trying to say that these models cannot generate images.
- In Section 9.3, the statement "The first term is a representation error that describes the error due to assuming (for signal reconstruction) that the signal x lies in the range of the generator, i.e., lies in the subspace for our setup." is a little confusing as this would imply zero representation error. Did you mean to say close to the subspace?
- This may be nitpicky, but stochastic gradient descent ascent isn't great for training GANs in practice. People tend to use negative momentum, optimism, ADAM, etc. 

Typos:
- Section 9.1, 9.2 "an decoder" -> "a decoder"
- Section 9.1 "an handcrafted" -> "a handcrafted"
- Section 9.1 "is thus is" -> "is thus"
- Section 9.2 "flow-baed" -> "flow-based"
- Section 9.2 "imaging application" -> "imaging applications"
- Figure 9.2 has D(z) for the generator instead of G(z)
-

**Comment by reinhardh** [comment]
Thanks for this feedback Jalal, this is super helpful! I fixed all those issues.
