### ISSUE TITLE
(minor) Repetitive Statement, Chapter 6

### ISSUE THREAD

**Issue by Soxxes** [MLI-lab/deep_inverse_book.github.io#2]
The following sentence contains a repetitive statement of $z_i$ beeing iid Gaussian (chapter 6.1):
![grafik](https://github.com/MLI-lab/deep_inverse_book.github.io/assets/50017993/922de7e4-94da-4d90-97ae-ccd2066da0d4)

**Comment by reinhardh** [comment]
Fixed, thanks!
