### ISSUE TITLE
definitions: untrained v. self-supervised

### ISSUE THREAD

**Issue by davevanveen** [MLI-lab/deep_inverse_book.github.io#7]
in general there doesn't seem to be clean, widely accepted definitions of untrained v. unsupervised v. self-supervised. personally i think of self-supervised as a subset of unsupervised learning where the learning process is guided by creating proxy tasks or designing artificial labels from the data itself. you define untrained methods as a subset of self-supervised methods, which i find interesting. ultimately it's all semantics, but you have a cool opportunity to establish proper definitions in your book. might be nice to make this explicit, or at least reference untrained/unsupervised methods in your intro to ch. 8 so the distinction is clearer.

**Comment by reinhardh** [comment]
Many thanks, very good point. I addressed that by justifying the naming in the respective chapters, and am also considering to explain that in the introduction.
