### ISSUE TITLE
ch. 9) overlap w dimakis textbook chapter

### ISSUE THREAD

**Issue by davevanveen** [MLI-lab/deep_inverse_book.github.io#8]
chapter 9 of your text has significant overlap w chapter 9 (by dimakis) of the book linked below. perhaps worth referencing or comparing against dimakis' formulation. i find both are written very well.

https://www.cambridge.org/core/books/abs/mathematical-aspects-of-deep-learning/deep-generative-models-and-inverse-problems/82AA3CBF820B7C8EF966E8A19330DB15

@article{dimakis2022deep,
  title={Deep Generative Models and Inverse Problems},
  author={Dimakis, Alexandros G and Bora, Ashish and Van Veen, Dave and Jalal, Ajil and Vishwanath, Sriram and Price, Eric},
  journal={Mathematical Aspects of Deep Learning},
  pages={400},
  year={2022},
  publisher={Cambridge University Press}
}

**Comment by reinhardh** [comment]
Thanks, I now read the chapter and think there is litte overlap also both chapters discuss similar topics. Alex's very nice chapter discusses sparsity, untrained networks, and imposing generative priors. Chapter 9 only focuses on imposing generative priors, and the structure is different.
