### ISSUE TITLE
ch. 11) context / motivation for coordinate mlp's

### ISSUE THREAD

**Issue by davevanveen** [MLI-lab/deep_inverse_book.github.io#9]
in your intro to coordinate mlp's (ch. 11), could be worthwhile providing more context. i.e. that these methods were originally developed for computationally-heavy tasks in graphics (e.g. nerf). compared to cnn's, their generality can allow for greater representational capacity in higher dimensions, etc.

**Comment by reinhardh** [comment]
Fixed, thanks!
